name: Daily Weather Notification

on:
  schedule:
    - cron: '30 22 * * *'  # In UTC this is 10:30 PM (22:30) UTC
  workflow_dispatch:

jobs:
  send_weather_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send weather notification request
        run: |
          curl -X GET "https://tinynotie-api.vercel.app/openai/getWeatherNotification"
